package com.lucassimoesmartins.deliciousrecipes.retrofit.service

import com.lucassimoesmartins.deliciousrecipes.constants.Constants
import com.lucassimoesmartins.deliciousrecipes.model.Recipe
import retrofit2.Call
import retrofit2.http.GET
import retrofit2.http.Query

interface Service {

    @GET("recipes/complexSearch?apiKey=${Constants.API_KEY}")
    fun getRecipesComplexSearch(
        @Query("query") query: String? = null,
        @Query("cuisine") cuisine: String? = null,
        @Query("excludeCuisine") excludeCuisine: String? = null,
        @Query("diet") diet: String? = null,
        @Query("intolerances") intolerances: String? = null,
        @Query("equipment") equipment: String? = null,
        @Query("includeIngredients") includeIngredients: String? = null,
        @Query("excludeIngredients") excludeIngredients: String? = null,
        @Query("type") type: String? = null,
        @Query("maxReadyTime") maxReadyTime: Int? = null,
        @Query("sort") sort: String? = null,
        @Query("sortDirection") sortDirection: String? = null,
        @Query("offset") offset: Int? = null,

        @Query("number") number: Int = 10,
        @Query("instructionsRequired") instructionsRequired: Boolean = true,
        @Query("fillIngredients") fillIngredients: Boolean = true,
        @Query("addRecipeInformation") addRecipeInformation: Boolean = true,
        @Query("ignorePantry") ignorePantry: Boolean = false
//        @Query("author") author: String,
//        @Query("tags") tags: String,
//        @Query("recipeBoxId") recipeBoxId: Int,
//        @Query("titleMatch") titleMatch: String,
//        @Query("limitLicense") limitLicense: Boolean,
//        @Query("minCarbs") minCarbs: Int,
//        @Query("maxCarbs") maxCarbs: Int,
//        @Query("minProtein") minProtein: Int,
//        @Query("maxProtein") maxProtein: Int,
//        @Query("minCalories") minCalories: Int,
//        @Query("maxCalories") maxCalories: Int,
//        @Query("minFat") minFat: Int,
//        @Query("maxFat") maxFat: Int,
//        @Query("minAlcohol") minAlcohol: Int,
//        @Query("maxAlcohol") maxAlcohol: Int,
//        @Query("minCaffeine") minCaffeine: Int,
//        @Query("maxCaffeine") maxCaffeine: Int,
//        @Query("minCopper") minCopper: Int,
//        @Query("maxCopper") maxCopper: Int,
//        @Query("minCalcium") minCalcium: Int,
//        @Query("maxCalcium") maxCalcium: Int,
//        @Query("minCholine") minCholine: Int,
//        @Query("maxCholine") maxCholine: Int,
//        @Query("minCholesterol") minCholesterol: Int,
//        @Query("maxCholesterol") maxCholesterol: Int,
//        @Query("minFluoride") minFluoride: Int,
//        @Query("maxFluoride") maxFluoride: Int,
//        @Query("minSaturatedFat") minSaturatedFat: Int,
//        @Query("maxSaturatedFat") maxSaturatedFat: Int,
//        @Query("minVitaminA") minVitaminA: Int,
//        @Query("maxVitaminA") maxVitaminA: Int,
//        @Query("minVitaminC") minVitaminC: Int,
//        @Query("maxVitaminC") maxVitaminC: Int,
//        @Query("minVitaminD") minVitaminD: Int,
//        @Query("maxVitaminD") maxVitaminD: Int,
//        @Query("minVitaminE") minVitaminE: Int,
//        @Query("maxVitaminE") maxVitaminE: Int,
//        @Query("minVitaminK") minVitaminK: Int,
//        @Query("maxVitaminK") maxVitaminK: Int,
//        @Query("minVitaminB1") minVitaminB1: Int,
//        @Query("maxVitaminB1") maxVitaminB1: Int,
//        @Query("minVitaminB2") minVitaminB2: Int,
//        @Query("maxVitaminB2") maxVitaminB2: Int,
//        @Query("minVitaminB5") minVitaminB5: Int,
//        @Query("maxVitaminB5") maxVitaminB5: Int,
//        @Query("minVitaminB3") minVitaminB3: Int,
//        @Query("maxVitaminB3") maxVitaminB3: Int,
//        @Query("minVitaminB6") minVitaminB6: Int,
//        @Query("maxVitaminB6") maxVitaminB6: Int,
//        @Query("minVitaminB12") minVitaminB12: Int,
//        @Query("maxVitaminB12") maxVitaminB12: Int,
//        @Query("minFiber") minFiber: Int,
//        @Query("maxFiber") maxFiber: Int,
//        @Query("minFolate") minFolate: Int,
//        @Query("maxFolate") maxFolate: Int,
//        @Query("minFolicAcid") minFolicAcid: Int,
//        @Query("maxFolicAcid") maxFolicAcid: Int,
//        @Query("minIodine") minIodine: Int,
//        @Query("maxIodine") maxIodine: Int,
//        @Query("minIron") minIron: Int,
//        @Query("maxIron") maxIron: Int,
//        @Query("minMagnesium") minMagnesium: Int,
//        @Query("maxMagnesium") maxMagnesium: Int,
//        @Query("minManganese") minManganese: Int,
//        @Query("maxManganese") maxManganese: Int,
//        @Query("minPhosphorus") minPhosphorus: Int,
//        @Query("maxPhosphorus") maxPhosphorus: Int,
//        @Query("minPotassium") minPotassium: Int,
//        @Query("maxPotassium") maxPotassium: Int,
//        @Query("minSelenium") minSelenium: Int,
//        @Query("maxSelenium") maxSelenium: Int,
//        @Query("minSodium") minSodium: Int,
//        @Query("maxSodium") maxSodium: Int,
//        @Query("minSugar") minSugar: Int,
//        @Query("maxSugar") maxSugar: Int,
//        @Query("minZinc") minZinc: Int,
//        @Query("maxZinc") maxZinc: Int,

    ): Call<Recipe>

}